### ISSUE TITLE
mmkubertnetes: action fails preparation cycle if kubernetes API destroys resource during bootup sequence

### ISSUE THREAD

**Issue by xytis** [rsyslog/rsyslog#2949]
### Expected behavior
mmkubernetes action loads up and completes `actionPrepare` without error.

### Actual behavior
```
$ kubectl delete pod rsyslog-hr8rw
# DaemonSet creates a new container in place of above one: 'rsyslog-pvng4'
$ kubectl logs rsyslog-pvng4 -p
rsyslogd 8.37.0: running as pid 1, enabling container-specific defaults, press ctl-c to terminate rsyslog
rsyslogd: mmkubernetes: Not Found: the resource does not exist at url [https://kubernetes.default.svc.cluster.local:443/api/v1/namespaces/logging/pods/rsyslog-hr8rw]  [v8.37.0]
rsyslogd: action 'k8s_metadata_append' (module 'mmkubernetes') message lost, could not be processed. Check for additional error messages before this one. [v8.37.0]
```

### Steps to reproduce the behavior
Run rsyslog inside docker container under kubernetes with these mounts to support `module imjournal`:
```
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: rsyslog
  labels:
    k8s-app: rsyslog
    kubernetes.io/cluster-service: "true"
spec:
  minReadySeconds: 30
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      k8s-app: rsyslog
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      labels:
        k8s-app: rsyslog
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: node-role.kubernetes.io/loadbalancer
          effect: NoSchedule
      priorityClassName: system-node-critical
      serviceAccountName: rsyslog
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: rsyslog
        image: jumanjiman/rsyslog
        command: ["rsyslogd", "-n", "-f", "/rsyslog/etc/rsyslogd.conf"]
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: host-etc-machine-id
          mountPath: /etc/machine-id
          readOnly: true
        - name: host-etc-hostname
          mountPath: /etc/hostname
          readOnly: true
        - name: host-var-log-journal
          mountPath: /var/log/journal
          readOnly: true
        - name: host-run-log-journal
          mountPath: /run/log/journal
          readOnly: true
        - name: host-run-systemd-journal
          mountPath: /run/systemd/journal
          readOnly: true
        - name: host-shared-folder
          mountPath: /var/rsyslog/
        - name: config-volume
          mountPath: /rsyslog/etc/
      volumes:
      - name: host-etc-machine-id
        hostPath:
          path: /etc/machine-id
      - name: host-etc-hostname
        hostPath:
          path: /etc/hostname
      - name: host-var-log-journal
        hostPath:
          path: /var/log/journal
      - name: host-run-log-journal
        hostPath:
          path: /run/log/journal
      - name: host-run-systemd-journal
        hostPath:
          path: /run/systemd/journal
      - name: host-shared-folder
        hostPath:
          path: /var/rsyslog/
      - name: config-volume
        configMap:
          name: rsyslog
```

Configuration example:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: rsyslog
  namespace: logging
data:
  rsyslogd.conf: |
    # Requires a working mount of /run/systemd/journal/socket
    module(
      load="imjournal"
      PersistStateInterval="100"
      IgnorePreviousMessages="on"
      StateFile="/var/rsyslog/journal.state"
      Ratelimit.Interval="0"
    )
    module(load="imuxsock")
    module(load="mmjsonparse")
    module(
      load="mmkubernetes"
      tls.cacert="/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      tokenfile="/run/secrets/kubernetes.io/serviceaccount/token"
    )

    global(parser.PermitSlashInProgramname="on")
    global(maxMessageSize="64k")

    template(name="json" type="subtree" subtree="$!")
    template(name="date" type="list"){
      property(name="timereported" dateFormat="rfc3339")
    }

    main_queue(
      queue.workerthreads="1"       # threads to work on the queue
      queue.dequeueBatchSize="1000" # max number of messages to process at once
      queue.size="10000"            # max queue size
    )

    set $!timestamp = exec_template("date");
    set $!host = getenv("HOSTNAME");
    set $!program = $programname;

    action(
      name="parse_json"
      type="mmjsonparse"
      cookie=""
    )

    action(
      name="k8s_metadata_append"
      type="mmkubernetes"
    )

    action(
      type="omfile"
      path="/tmp/log"
      template="json"
    )

```

RBAC:
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rsyslog
  labels:
    k8s-app: rsyslog
    kubernetes.io/cluster-service: "true"
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rsyslog
  labels:
    k8s-app: rsyslog
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: rsyslog
  namespace: logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: rsyslog
  apiGroup: ""
```
### Environment
- rsyslog version: 8.37.0
- platform: alpine linux (docker container)
