### ISSUE TITLE
Pushing logs to Loki

### ISSUE THREAD

**Issue by dmolik** [rsyslog/rsyslog#3976]
So I've started investigating sending logs to [Loki](https://github.com/grafana/loki) and as previously mentioned on the mailing list, it's a relatively simple configuration to omhttp:

So a simple config to get one started would be:

    template(name="echo_loki" type="string"
        string="{\"streams\":[{
             \"stream\": {\"host\": \"%HOSTNAME%\",\"facility\":\"%syslogfacility-text%\",\"priority\":\"%syslogpriority-text%\",\"syslogtag\":\"%syslogtag%\"},
             \"values\": [[ \"%timegenerated:::date-unixtimestamp%000000000\", \"%msg%\" ]]}]}\n")
   
    *.* action(
    	name="loki"
    	type="omhttp"
    	useHttps="off"
    	server="localhost"
    	serverport="3100"
    	checkpath="ready"
    	httpcontenttype="application/json"
    	restpath="loki/api/v1/push"
     	template="echo_loki"
    )

and for loki:
```
auth_enabled: false

server:
  http_listen_port: 3100
  #log_level: warn

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
```

Now one might notice that omhttp bulk processing is not turned on. This is due to the wiggly nature of the loki spec. See: https://github.com/grafana/loki/blob/master/docs/api.md#post-lokiapiv1push, which basically means that a json array needs to be preceded by the `streams` key, but also that every log line has two parts: the `stream` index keys, and the `values` which makes templating for a "lokirest" `batch.format` a little finicky. I landed up creating a local patch to test, the array template looks like this:
```
template(name="array_loki" type="string" string="{\"stream\":{\"host\":\"%HOSTNAME%\",\"facility\":\"%syslogfacility-text%\",\"priority\":\"%syslogpriority-text%\",\"syslogtag\":\"%syslogtag%\"},\"values\": [[ \"%timegenerated:::date-unixtimestamp%000000000\", \"%msg%\" ]]}")
```
And the patching was based off of the kafkarest bits in omhttp. I can post if anyone is interested.

So I'm wondering if someone has an idea around this, perhaps a new module? or smarter changes to omhttp. I don't like relying on pipeline developers to get the template format correct.

### Environment
- rsyslog version: 8.1911.0
- platform: Gentoo
- for configuration questions/issues, include rsyslog.conf and included config files
