### ISSUE TITLE
[bug] imfile: internal error? inotify provided watch descriptor NNN which we could not find in our tables

### ISSUE THREAD

**Issue by selivan** [rsyslog/rsyslog#4222]
### Expected behavior

Work without errors

### Actual behavior

Errors like this:

```
imfile: internal error? inotify provided watch descriptor 272 which we could not find in our tables - ignored [v8.2001.0 try https://www.rsyslog.com/e/2175 ]
imfile: internal error? inotify provided watch descriptor 261 which we could not find in our tables - ignored [v8.2001.0 try https://www.rsyslog.com/e/2175 ]
```

Periodically appear on out hosts. One time rsyslog produced a bunch of this error:

```
imfile: internal error? inotify provided watch descriptor 6 which we could not find in our tables - ignored [v8.2002.0 try https://www.rsyslog.com/e/2175 ]
```
About 3000 per hour. That instance of rsyslog stopped forwarding log files until it was reloaded.

https://www.rsyslog.com/e/2175 says "Rsyslogd internal error, unexpected code path reached".

### Steps to reproduce the behavior

I can not find a way to reproduce this error on purpose, it appears randomly.

### Environment
- rsyslog version: 8.2001.0 (aka 2020.01)
- platform: Ubuntu 16.04
- for configuration questions/issues, include rsyslog.conf and included config files

rsyslog.conf
```
$RepeatedMsgReduction off  # log every message
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog
$WorkDirectory /var/spool/rsyslog
$MaxOpenFiles 65535
$MaxMessageSize  128k
$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
module(load="imfile" mode="inotify")
module(load="builtin:omfile" FileOwner="syslog" FileGroup="adm" dirOwner="syslog" dirGroup="adm" FileCreateMode="0640" DirCreateMode="0755")
module(load="builtin:omfwd" template="LongTagForwardFormat")
module(load="omrelp")
module(load="mmexternal")
template (name="LongTagForwardFormat" type="string" string="<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%$.suffix%%msg:::sp-if-no-1st-sp%%msg%")
template(name="jsonSyslogTemplate" type="list") { ... }
template(name="jsonFileRawTemplate" type="list") { ... }
template(name="jsonFileJsonLineTemplate" type="list") { ... }
template(name="OnlyMsg" type="string" string="%msg:::drop-last-lf%\n")
ruleset(name="sendToLogserver") {
action(type="omrelp" Target="X.X.X.X" Port="NNN" Template="LongTagForwardFormat" queue.type="LinkedList" queue.size="5000" queue.filename="q_sendToLogserver" queue.highwatermark="4000" queue.lowwatermark="0" queue.maxdiskspace="512m" queue.saveonshutdown="on" action.resumeRetryCount="-1" action.reportSuspension="on" action.reportSuspensionContinuation="on" action.resumeInterval="10")
}
$IncludeConfig /etc/rsyslog.d/*.conf
call sendToLogserver
```

Files in rsyslogd.d look like this:
```
input(type="imfile"
File="/var/run/audit_logs/audit.log"
Tag="audispd"
Ruleset="audispd")

ruleset(name="audispd") {
      call sendToLogserver
}
```

**Comment by MrYueQ** [comment]
> error log 
```yaml
Oct 08 03:31:58 demo rsyslogd[25884]: imfile: internal error? inotify provided watch descriptor 755 which we could not find in our tables - ignored [v8.2010.0.master try https://www.rsyslog.com/e/2175 ]
Oct 08 03:31:58 demo rsyslogd[25884]: imfile: internal error? inotify provided watch descriptor 414 which we could not find in our tables - ignored [v8.2010.0.master try https://www.rsyslog.com/e/2175 ]
Oct 08 03:31:58 demo rsyslogd[25884]: imfile: internal error? inotify provided watch descriptor 874 which we could not find in our tables - ignored [v8.2010.0.master try https://www.rsyslog.com/e/2175 ]
```

> rsyslog version
```yaml
rsyslogd -v
rsyslogd  8.2010.0.master (aka 2020.10) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/syslogd.pid
        Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
```

> system info
```yaml
uname  -ar
Linux demo 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
