### ISSUE TITLE
omkafka: action will suspended due to kafka error -195: Local: Broker transport failure

### ISSUE THREAD

**Issue by MrYueQ** [rsyslog/rsyslog#4242]
## Error Info
```bash
Apr 11 18:43:32 hostname rsyslogd[29035]: omkafka: action will suspended due to kafka error -195: Local: Broker transport failure [v8.40.0 try https://www.rsyslog.com/e/2422 ]
Apr 11 18:43:32 hostname rsyslogd[29035]: action 'action-1-omkafka' suspended (module 'omkafka'), retry 0. There should be messages before this one giving the reason for suspension. [v8.40.0 try https://www.rsyslog.com/e/2007 ]
Apr 11 18:43:32 hostname rsyslogd[29035]: action 'action-1-omkafka' resumed (module 'omkafka') [v8.40.0 try https://www.rsyslog.com/e/2359 ]
```
## Rsyslog Info 
```yaml
# Rsyslog
rsyslogd -version 
rsyslogd 8.40.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Number of Bits in RainerScript integers: 64
# Rsyslog-kafka
rsyslog-kafka.x86_64              8.40.0-1.el7 
```
#3757

### Environment

```yaml
# Os system Verson
 uname -ar
Linux hostname 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Rsyslog config
```yaml
ruleset(name="ops-nginx-prod") {
    action (
        type="omkafka"
        confParam=[
            "compression.codec=snappy",
            "message.send.max.retries=3",
            "request.required.acks=1",
            "message.timeout.ms=600000",
            "socket.keepalive.enable=true"
        ]
        queue.spoolDirectory="/tmp"
        queue.filename="ops-nginx-prod-log"
        queue.size="100"
        queue.dequeuebatchsize="100"
        queue.timeoutenqueue="500"
        queue.saveonshutdown="on"
        queue.workerThreads="2"
        topic="ops-nginx-log"

        KeepFailedMessages="on"
        resubmitOnFailure="on"
        failedMsgFile="/var/lib/rsyslog/kafka_err_msg.log"
        action.resumeRetryCount="5"
        errorFile="/var/lib/rsyslog/nginx_prod_failures.log"
...
    )
}
```
