### ISSUE TITLE
CI/buildbot: do not run code checks if only doc-type files are modified

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#5713]
In github actions, we do this via 

```
on:
  pull_request:
    paths-ignore:
      - 'ChangeLog'
      - '**/*.md'
      - '**/*.txt'
```

As far as I know, there is a similiar capability in buildbot.
